### ISSUE TITLE
cache usage is not compatible to laravel 5.8

### ISSUE THREAD

**Issue by mbehnke** [abrigham1/laravel-email-exceptions#7]
throtteling doesnt work with caching in redis or file (Cache Class) because of changes in laravel framework from minutes to milisecs

idea: 'throttleDurationMinutes' => now()->addMinutes(5), etc.

For Documentation i recommand a compatibility matrix and dependecy checks

See also: https://github.com/laravel/framework/commit/fd6eb89b62ec09df1ffbee164831a827e83fa61d

**Comment by abrigham1** [comment]
@mbehnke  To avoid breaking current config's I've incorporated the change within the package instead of just updating the config/documentation. This has the drawback of not giving people as much fine grain control (throttling still needs to be defined in minutes), but no one should have to update their current config, just pull in version 1.2.2 of the package. Perhaps in a 2.0 version it could be switched to throttleDuration instead of throttleDurationMinutes. Feel free to run composer update and let me know if you have any issues.

**Comment by abrigham1** [comment]
@mbehnke I'll assume this resolved the issue for you, if not feel free to open a new one.

**Comment by mbehnke** [comment]
composer update solved my problem! Thanks
